# Front-end Dockerfile
# Step 1: Build the React app
FROM node:16-alpine as build
WORKDIR /app
COPY ./front-end/package.json ./front-end/package-lock.json ./
RUN npm install
COPY ./front-end ./
RUN npm run build

# Step 2: Serve the React app with nginx
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
