# Back-end Dockerfile
# Use a base image with Java
FROM openjdk:17-jdk-alpine
VOLUME /tmp
EXPOSE 8080

# Copy the built JAR file
COPY ./back-end/target/*.jar app.jar

# Run the JAR file
ENTRYPOINT ["java","-jar","/app.jar"]
